# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r_github_packages: stan-dev/cmdstanr

before_install:
- sudo apt-get -y install libv8-dev

install:
- travis_wait 

before_script:
- Rscript -e "install.packages('devtools'); devtools::install_github('stan-dev/cmdstanr')"
- Rscript -e "cmdstanr::install_cmdstan()"

	
