# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r_github_packages: stan-dev/cmdstanr

before_install:
- sudo apt-get -y install libv8-dev

install: travis_wait mvn install

before_script:
- Rscript -e "cmdstanr::install_cmdstan()"
	
# script: 
# - |
#   R CMD build --no-build-vignettes .
#   travis_wait 40 R CMD check --no--vignettes artemis*tar.gz