# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# repos:
#  stan: https://mc-stan.org/r-packages/

r_github_packages: stan-dev/cmdstanr
	
# after_success:
#   - Rscript -e 'covr::codecov()'
