# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

# r_packages:
# - devtools
# - ggplot2
# - rstan
# - rstantools
# - loo
# - lme4
# - rmarkdown

r_github_packages: stan-dev/cmdstanr

r_packages: covr

before_install:
- sudo apt-get -y install libv8-dev

install:
- travis_wait 

before_script:
- Rscript -e "install.packages(c('StanHeaders', 'Rccp', 'lme4', 'ggplot2', 'rstan', 'loo', 'rstantools','devtools', 'rmarkdown'))"

script:
  - |
    R CMD build .
	travis_wait 20 R CMD check artemis*.tar.gz

warnings_are_errors: false	

after_success:
- Rscript -e 'library(covr); codecov()'
